version: '3.8'
services:
  jupyter:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8899:8888"  # Changed from 8888:8888
      - "8090:8080"  # Changed from 8080:8080
    env_file:
      - .env
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token=''
