version: '3.8'
services:
  jupyter:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - PYTHONPATH=/opt/airflow
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/airflow/youtube-kids-pipeline-45aab0c99825.json
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
      - GCP_BUCKET_NAME=${GCP_BUCKET_NAME}
      - GCP_DATASET_ID=${GCP_DATASET_ID}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
    volumes:
      - .:/app
      - ./youtube-kids-pipeline-45aab0c99825.json:/opt/airflow/youtube-kids-pipeline-45aab0c99825.json:ro
    ports:
      - "8889:8888"
      - "8090:8080"
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token=''

  airflow:
    image: apache/airflow:2.7.2
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW_WWW_USER_USERNAME=${AIRFLOW_ADMIN_USERNAME}
      - AIRFLOW_WWW_USER_PASSWORD=${AIRFLOW_ADMIN_PASSWORD}
      - PYTHONPATH=/opt/airflow
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/airflow/youtube-kids-pipeline-45aab0c99825.json
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
      - GCP_BUCKET_NAME=${GCP_BUCKET_NAME}
      - GCP_DATASET_ID=${GCP_DATASET_ID}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./src:/opt/airflow/src
      - ./data:/opt/airflow/data
      - ./youtube-kids-pipeline-45aab0c99825.json:/opt/airflow/youtube-kids-pipeline-45aab0c99825.json:ro
    env_file:
      - .env
    ports:
      - "8084:8080"
    entrypoint: >
      bash -c "
      airflow db init &&
      airflow users create --username $$AIRFLOW_WWW_USER_USERNAME --password $$AIRFLOW_WWW_USER_PASSWORD --firstname Anonymous --lastname Admin --role Admin --email admin@example.com &&
      airflow scheduler & 
      exec airflow webserver"

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

volumes:
  postgres_data: